apply plugin: 'com.android.library'


version = "1.0.0"

def siteUrl = "https://github.com/SpongeBobSun/mCalendarView/"
def gitUrl = "https://github.com/SpongeBobSun/mCalendarView.git"
group = "sun.bob"

android {
    compileSdkVersion 33


    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 33
        resourcePrefix "23"
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.6.1'
}

task sourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    classifier = 'sources'
}
task javadoc(type: Javadoc) {
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
}
task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
}

javadoc {
    options{
        encoding "UTF-8"
        charSet 'UTF-8'
    }
}